### ISSUE TITLE
Error in parseResults(content$search_results) : could not find function "as.tbl"

### ISSUE THREAD

**Issue by alexbransky** [NoahZinsmeister/Rbnb#1]
When I execute: content = Rbnb::searchLocation(location, verbose=FALSE)
I get:
Error in parseResults(content$search_results) : 
  could not find function "as.tbl"

I'm sort of an R newbie so maybe it's something simple.

I'm using Rbnb 0.1.0 in RStudio and everything else is up to date as far as I can tell.

**Comment by JPIannaco** [comment]
Hi Alex,
I am having the exact same problem. Did you manage to solve it?

Thanks
JP

**Comment by NoahZinsmeister** [comment]
Hi @alexbransky, @JPIannaco, sorry for the slow response. I just pushed an update that should fix this issue, let me know if it didn't and I'll reopen the issue.

For reference, as.tbl is a function in dplyr's namespace.

**Comment by JPIannaco** [comment]
Hi @NoahZinsmeister. Thanks for the quick response and the quick update. It works now.
Cheers
JP
